Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 80, host: 8084

  config.vm.provision "docker" do |docker|
    docker.run "docker run -d --name sonarqube -p 9000:9000 sonarqube:lts", image: "sonarqube:lts"
  end
end
